### PR TITLE
add some missing steps to make installation tutorial better

### PR DESCRIPTION
**Pull request by XatMassacrE**
In order to let everyone run nebulas node easily

### CODE REVIEW

**Comment by fbzhong** [comment]
Hi @XatMassacrE,

Thanks for your PR.

I'd suggest use `cd go-nebulas` to jump into src dir of nebulas, instead of full path.

**Comment by fbzhong** [comment]
Can you change that?

**Comment by XatMassacrE** [comment]
@fbzhong ok

**Comment by XatMassacrE** [comment]
@fbzhong Finished.

**Comment by fbzhong** [comment]
👍

**Pull request merged**
